const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '../change 2fa community/static');
const app = fs.readFileSync(path.join(root,'app.js'),'utf8');
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const css = fs.readFileSync(path.join(root,'dashboard.css'),'utf8');
assert.match(css, /#passkey-open\[hidden\]\{display:none\}/);
assert.match(app,/data-action="passkey"/);
assert.match(app,/confirm: 'ADD_PASSKEY'/);
assert.match(app,/\/passkey\/start/);
assert.match(app,/passkey_preparing/);
assert.match(html,/\/assets\/tabler-icons\.svg\?v=1\.0\.3#ti-/);
assert.match(html,/id="passkey-confirm"[^>]*aria-labelledby="passkey-title"/);
assert.match(html,/id="passkey-open"[^>]*target="_blank"[^>]*rel="noopener noreferrer"/);
assert.match(app,/removeAttribute\('href'\)/);
assert.match(html,/Chưa xác nhận đã thêm passkey/);
assert.match(html,/Touch ID\/Face ID/);
assert.match(html,/Advanced Account Security/);
assert.doesNotMatch(app,/credentials\.create|privateKey/);
console.log('passkey UI: explicit handoff, key privacy, cleanup, no false completion passed');
